name: FTP deploy on push   
on: push   
jobs:   
  web-deploy:   
    name: Deploy   
    runs-on: ubuntu-latest   
    steps:   
    - name: Get latest code   
      uses: actions/checkout@v3   
    - name: Sync files   
      uses: sebastianpopp/git-ftp-action@releases/v3   
      with:   
        server: 'br511583.ftp.tools'   
        username: 'br511583_ftp'   
        password: 'C8399uJjFf'   
        server-dir: '/seo-top.com.ua/www/'
